name: false-labels
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - ipykernel
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - PyYAML
  - python
  - scikit-learn
  - tensorflow>=2.5
  - tqdm